import {
  AdminCategory,
  AdminCustomer,
  AdminOrder,
  AdminProduct,
  AdminReview,
  NavLink,
} from "./types";

export const mockProducts: AdminProduct[] = [
  {
    id: 1,
    title: "Predator Elite FG Boots",
    srcUrl: "/images/football/boot.svg",
    category: "Boots & Cleats",
    brand: "adidas",
    condition: "used",
    size: "UK 9",
    price: 18500,
    discountPercentage: 0,
    stock: 6,
    status: "active",
    rating: 4.5,
  },
  {
    id: 2,
    title: "Mercurial Vapor 15 Boots",
    srcUrl: "/images/football/boot.svg",
    category: "Boots & Cleats",
    brand: "Nike",
    condition: "used",
    size: "UK 8",
    price: 22000,
    discountPercentage: 15,
    stock: 4,
    status: "active",
    rating: 4.5,
  },
  {
    id: 3,
    title: "Home Match Jersey 23/24",
    srcUrl: "/images/football/jersey.svg",
    category: "Jerseys & Kits",
    brand: "adidas",
    condition: "new",
    size: "M",
    price: 6500,
    discountPercentage: 0,
    stock: 0,
    status: "draft",
    rating: 4.5,
  },
  {
    id: 4,
    title: "Away Match Jersey 23/24",
    srcUrl: "/images/football/jersey.svg",
    category: "Jerseys & Kits",
    brand: "Nike",
    condition: "new",
    size: "L",
    price: 7000,
    discountPercentage: 0,
    stock: 20,
    status: "active",
    rating: 5,
  },
  {
    id: 5,
    title: "Match Football (Size 5)",
    srcUrl: "/images/football/ball.svg",
    category: "Balls",
    brand: "PUMA",
    condition: "new",
    size: "Size 5",
    price: 4500,
    discountPercentage: 0,
    stock: 35,
    status: "active",
    rating: 4,
  },
  {
    id: 6,
    title: "Goalkeeper Gloves Pro",
    srcUrl: "/images/football/gloves.svg",
    category: "Goalkeeper Gloves",
    brand: "Under Armour",
    condition: "used",
    size: "M",
    price: 5000,
    discountPercentage: 10,
    stock: 12,
    status: "active",
    rating: 4,
  },
];

export const mockCategories: AdminCategory[] = [
  {
    id: 1,
    name: "Boots & Cleats",
    slug: "boots-cleats",
    description: "Football boots and cleats for every surface.",
    productCount: 2,
  },
  {
    id: 2,
    name: "Jerseys & Kits",
    slug: "jerseys-kits",
    description: "Home, away, and training kits.",
    productCount: 2,
  },
  {
    id: 3,
    name: "Balls",
    slug: "balls",
    description: "Match and training footballs.",
    productCount: 1,
  },
  {
    id: 4,
    name: "Goalkeeper Gloves",
    slug: "goalkeeper-gloves",
    description: "Gloves for shot-stoppers.",
    productCount: 1,
  },
  {
    id: 5,
    name: "Shin Guards",
    slug: "shin-guards",
    description: "Protective shin guards.",
    productCount: 0,
  },
];

export const mockNavLinks: NavLink[] = [
  {
    id: 1,
    label: "Football",
    url: "/shop",
    children: [
      { id: 11, label: "Men's Football", url: "/shop#men-football" },
      { id: 12, label: "Women's Football", url: "/shop#women-football" },
      { id: 13, label: "Kids' Football", url: "/shop#kids-football" },
      { id: 14, label: "Balls & Accessories", url: "/shop#balls-accessories" },
    ],
  },
  { id: 2, label: "On Sale", url: "/shop#on-sale", children: [] },
  { id: 3, label: "New Arrivals", url: "/shop#new-arrivals", children: [] },
  { id: 4, label: "Brands", url: "/shop#brands", children: [] },
];

export const mockReviews: AdminReview[] = [
  {
    id: 1,
    user: "Alex K.",
    product: "Predator Elite FG Boots",
    content:
      "Ordered a pair of used boots and they arrived exactly as described. Guaranteed original, no doubts.",
    rating: 5,
    date: "2023-08-14",
    status: "published",
  },
  {
    id: 2,
    user: "Sarah M.",
    product: "Mercurial Vapor 15 Boots",
    content:
      "Great price for pre-owned gear, and the sizing guide was spot on.",
    rating: 5,
    date: "2023-08-15",
    status: "published",
  },
  {
    id: 3,
    user: "Ethan R.",
    product: "Home Match Jersey 23/24",
    content: "Brand new with tags, exactly as listed. Fast delivery too.",
    rating: 4,
    date: "2023-08-16",
    status: "published",
  },
  {
    id: 4,
    user: "Olivia P.",
    product: "Away Match Jersey 23/24",
    content: "Good quality but sizing ran a bit large for me.",
    rating: 3,
    date: "2023-08-17",
    status: "hidden",
  },
  {
    id: 5,
    user: "Liam K.",
    product: "Match Football (Size 5)",
    content: "Holds up well after weeks of daily training use.",
    rating: 5,
    date: "2023-08-18",
    status: "published",
  },
];

export const mockBanner = {
  enabled: true,
  text: "Sign up and get 20% off to your first order.",
  ctaLabel: "Sign Up Now",
  ctaUrl: "#",
};

export const mockBranding = {
  storeName: "SHOP.CO",
  tagline:
    "Boots, jerseys, and match-day gear from top brands — carefully inspected and guaranteed authentic.",
  logoUrl: "",
  faviconUrl: "",
};

export const mockStoreDetails = {
  email: "support@shopco.com",
  phone: "+1 (555) 010-2020",
  address: "",
  city: "",
  state: "",
  zip: "",
  country: "",
  social: {
    twitter: "https://twitter.com",
    facebook: "https://facebook.com",
    instagram: "https://instagram.com",
  },
};

export const mockCustomers: AdminCustomer[] = [
  {
    id: 1,
    name: "Alex K.",
    email: "alex.k@example.com",
    ordersCount: 2,
    totalSpent: 40500,
    joinedDate: "2023-02-11",
    status: "active",
  },
  {
    id: 2,
    name: "Sarah M.",
    email: "sarah.m@example.com",
    ordersCount: 2,
    totalSpent: 42000,
    joinedDate: "2023-04-02",
    status: "active",
  },
  {
    id: 3,
    name: "Ethan R.",
    email: "ethan.r@example.com",
    ordersCount: 1,
    totalSpent: 6500,
    joinedDate: "2024-01-19",
    status: "active",
  },
  {
    id: 4,
    name: "Olivia P.",
    email: "olivia.p@example.com",
    ordersCount: 1,
    totalSpent: 13500,
    joinedDate: "2022-11-27",
    status: "active",
  },
  {
    id: 5,
    name: "Liam K.",
    email: "liam.k@example.com",
    ordersCount: 1,
    totalSpent: 0,
    joinedDate: "2023-09-08",
    status: "blocked",
  },
  {
    id: 6,
    name: "Samantha D.",
    email: "samantha.d@example.com",
    ordersCount: 1,
    totalSpent: 32500,
    joinedDate: "2023-06-15",
    status: "active",
  },
];

export const mockOrders: AdminOrder[] = [
  {
    id: 1,
    orderNumber: "#3210",
    customerName: "Alex K.",
    customerEmail: "alex.k@example.com",
    items: [
      { productTitle: "Predator Elite FG Boots", quantity: 1, price: 18500 },
    ],
    total: 18500,
    status: "delivered",
    date: "2024-06-02",
  },
  {
    id: 2,
    orderNumber: "#3211",
    customerName: "Sarah M.",
    customerEmail: "sarah.m@example.com",
    items: [
      { productTitle: "Mercurial Vapor 15 Boots", quantity: 1, price: 22000 },
      { productTitle: "Away Match Jersey 23/24", quantity: 1, price: 7000 },
    ],
    total: 29000,
    status: "shipped",
    date: "2024-06-05",
  },
  {
    id: 3,
    orderNumber: "#3212",
    customerName: "Ethan R.",
    customerEmail: "ethan.r@example.com",
    items: [
      { productTitle: "Home Match Jersey 23/24", quantity: 1, price: 6500 },
    ],
    total: 6500,
    status: "pending",
    date: "2024-06-08",
  },
  {
    id: 4,
    orderNumber: "#3213",
    customerName: "Olivia P.",
    customerEmail: "olivia.p@example.com",
    items: [
      { productTitle: "Match Football (Size 5)", quantity: 3, price: 4500 },
    ],
    total: 13500,
    status: "processing",
    date: "2024-06-10",
  },
  {
    id: 5,
    orderNumber: "#3214",
    customerName: "Liam K.",
    customerEmail: "liam.k@example.com",
    items: [
      { productTitle: "Goalkeeper Gloves Pro", quantity: 1, price: 5000 },
    ],
    total: 5000,
    status: "cancelled",
    date: "2024-06-11",
  },
  {
    id: 6,
    orderNumber: "#3215",
    customerName: "Samantha D.",
    customerEmail: "samantha.d@example.com",
    items: [
      { productTitle: "Away Match Jersey 23/24", quantity: 2, price: 7000 },
      { productTitle: "Predator Elite FG Boots", quantity: 1, price: 18500 },
    ],
    total: 32500,
    status: "delivered",
    date: "2024-06-14",
  },
  {
    id: 7,
    orderNumber: "#3216",
    customerName: "Alex K.",
    customerEmail: "alex.k@example.com",
    items: [
      { productTitle: "Mercurial Vapor 15 Boots", quantity: 1, price: 22000 },
    ],
    total: 22000,
    status: "shipped",
    date: "2024-06-17",
  },
  {
    id: 8,
    orderNumber: "#3217",
    customerName: "Sarah M.",
    customerEmail: "sarah.m@example.com",
    items: [
      { productTitle: "Home Match Jersey 23/24", quantity: 2, price: 6500 },
    ],
    total: 13000,
    status: "pending",
    date: "2024-06-19",
  },
];
